// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// If the Vite env vars are present, create the real Supabase client.
// Otherwise export a safe fallback that prevents app crash and returns
// empty/no-op responses so the app can run while you migrate to your
// own backend APIs.
let supabase: any;

if (SUPABASE_URL) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  // Minimal no-op fallback used when Supabase env vars are not provided.
  const noopResult = { data: null, error: null };

  const createThenableResult = () => {
    const p = Promise.resolve(noopResult);
    // make thenable
    return { then: p.then.bind(p), catch: p.catch.bind(p) } as any;
  };

  const createQueryBuilder = () => {
    const builder: any = {
      _table: null,
      _selectArgs: null,
      _filters: [] as any[],
    };

    const chainable = (name: string) => (..._args: any[]) => { builder._filters.push([name, ..._args]); return chainableObj; };

    const exec = async () => noopResult;

    const chainableObj: any = {
      select: (...args: any[]) => { builder._selectArgs = args; return chainableObj; },
      eq: chainable('eq'),
      neq: chainable('neq'),
      in: chainable('in'),
      order: chainable('order'),
      limit: chainable('limit'),
      range: chainable('range'),
      maybeSingle: async () => noopResult,
      single: async () => noopResult,
      then: (resolve: any, reject: any) => Promise.resolve(noopResult).then(resolve, reject),
      catch: (cb: any) => Promise.resolve(noopResult).catch(cb),
    };

    return chainableObj;
  };

  const createChannelBuilder = (name: string, _opts?: any) => {
    const ch: any = {
      name,
      handlers: [] as any[],
      on: function(event: any, filterOrPayload?: any, callback?: any) {
        // support both .on(event, payload, cb) and .on(event, cb)
        if (typeof filterOrPayload === 'function') {
          ch.handlers.push({ event, callback: filterOrPayload });
        } else {
          ch.handlers.push({ event, filter: filterOrPayload, callback });
        }
        return ch;
      },
      subscribe: async function() {
        return { id: name };
      }
    };
    return ch;
  };

  supabase = {
    from: (_table: string) => createQueryBuilder(),
    storage: {
      from: (_bucket: string) => ({
        upload: async () => noopResult,
        download: async () => noopResult,
        list: async () => ({ data: [], error: null }),
        remove: async () => noopResult,
      })
    },
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null } }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signOut: async () => ({ error: null }),
      signIn: async () => noopResult,
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: { message: 'Supabase login is not configured for this environment.' },
      }),
      signUp: async () => noopResult,
      updateUser: async () => noopResult,
      refreshSession: async () => ({ data: { session: null }, error: null }),
      setSession: async () => ({ data: { session: null }, error: null }),
    },
    rpc: async () => noopResult,
    removeChannel: (_ch: any) => {},
    channel: (name: string, opts?: any) => createChannelBuilder(name, opts),
  };

  // Provide a development-time console hint to aid migration.
  // eslint-disable-next-line no-console
  console.warn('[supabase] VITE_SUPABASE_URL not set — using no-op fallback.');
}

export { supabase };
